# Welcome New Contributors
name: Greetings

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
      - uses: actions/first-interaction@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: 'Welcome to CryptoFaucet Hub! 🎉 Thanks for opening this issue. Please provide as much detail as possible so we can help you.'
          pr-message: 'Welcome to CryptoFaucet Hub! 🎉 Thanks for creating this pull request. Our team will review it soon.'
